#!/usr/bin/env python

from lib import Config
from lib import Database
from lib import Lodestone

db = Database()
config = Config()
ls = Lodestone(config.character(), config.session_id())

for retainer in config.retainer_ids():
  history = ls.sales_history(retainer=retainer)
  for item in history:
    db.add_sold_item(item)
