---
session: "your lodestone session id"
character: "id of your character"
retainers:
  f49f0239a5: Lominsaret
  ad32977801: Chimomo
  6f49aebcb1: Liwita
  f2d1754992: Chookity
log_directory: /home/yitsushi/.data/ffxiv/efertone/log
data_directory: /home/yitsushi/.data/ffxiv/efertone/data
